// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdcYSpJdKmxjpYFIiLuRjYz6Vp6xcM0FA',
    appId: '1:197567944362:web:aad8b6a2027a42dda122d3',
    messagingSenderId: '197567944362',
    projectId: 'social-media-api-383221',
    authDomain: 'social-media-api-383221.firebaseapp.com',
    storageBucket: 'social-media-api-383221.appspot.com',
    measurementId: 'G-K0WMT4H4TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUO-Y-U10m_2VtFetBPw3fHwnGFOOv4Tk',
    appId: '1:197567944362:android:17be9a2785c820a1a122d3',
    messagingSenderId: '197567944362',
    projectId: 'social-media-api-383221',
    storageBucket: 'social-media-api-383221.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH0s9t8Vdnjzm1wpAPaYF7V_k03cQtASo',
    appId: '1:197567944362:ios:fff1c1ee2543dee5a122d3',
    messagingSenderId: '197567944362',
    projectId: 'social-media-api-383221',
    storageBucket: 'social-media-api-383221.appspot.com',
    iosClientId: '197567944362-8sklrj8qq3bdlm8stmk7sagj7r5fq2gk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTutorials',
  );
}
